### ISSUE TITLE
Docs build on docs.rs is failing

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/ibc-types#56]
See example failure here: https://docs.rs/crate/ibc-types/0.6.1/builds/915166 

```
[INFO] [stderr] warning: Target filter specified, but no targets matched. This is a no-op
[INFO] [stderr]     Checking bytes v1.5.0
[INFO] [stderr]     Checking serde_bytes v0.11.12
[INFO] [stderr]     Checking serde_json v1.0.107
[INFO] [stderr]     Checking ed25519-consensus v2.1.0
[INFO] [stderr]    Compiling safe-proc-macro2 v1.0.36
[INFO] [stderr]    Compiling crunchy v0.2.2
[INFO] [stderr] error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/safe-proc-macro2-1.0.36/src/wrapper.rs:485:33
[INFO] [stderr]     |
[INFO] [stderr] 485 |                 let proc_macro::LineColumn { line, column } = s.start();
[INFO] [stderr]     |                                 ^^^^^^^^^^ not found in `proc_macro`
[INFO] [stderr]     |
[INFO] [stderr] help: consider importing one of these items
[INFO] [stderr]     |
[INFO] [stderr] 1   + use crate::LineColumn;
[INFO] [stderr]     |
[INFO] [stderr] 1   + use crate::fallback::LineColumn;
[INFO] [stderr]     |
[INFO] [stderr] help: if you import `LineColumn`, refer to it directly
[INFO] [stderr]     |
[INFO] [stderr] 485 -                 let proc_macro::LineColumn { line, column } = s.start();
[INFO] [stderr] 485 +                 let LineColumn { line, column } = s.start();
[INFO] [stderr]     |
[INFO] [stderr] 
```

Looks like we should bump `proc-macro2` within the deps.

**Comment by conorsch** [comment]
PR should resolve it. Looks like the docs.rs build process is using a version of `proc-macro2` that's a bit too old. We don't commit lockfiles for these libraries, so instead I added a recent version of `proc-macro2` to the deps of `ibc-types-core-channel`. However, we won't know the problem is fixed until we post another release, thereby triggering the docs.rs build.

**Comment by conorsch** [comment]
[Still failing](https://docs.rs/crate/ibc-types/0.6.2/builds/916185):

![ibc-types-docsrs-failure](https://github.com/penumbra-zone/ibc-types/assets/657862/a6de19d1-d870-42f6-b9d2-1fda8dda26f3)

**Comment by rnbguy** [comment]
Hey, this is coming from `safe-proc-macro2`(dependency of `safe-regex`) which was using removed `proc_macro::LineColumn`. It is not related to `proc-macro2`.

The author has made a new release. If you're not using cargo.lock, the next release should publish just fine on docs.rs. Otherwise just do a `cargo update` to fetch the latest `safe-proc-macro2`.

**Comment by conorsch** [comment]
Thanks for explaining! We're not using a lockfile, since these crates are libraries, not binaries, and that's what the [cargo book recommends](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). It's not clear to me how to force docs.rs to run `cargo update` in the build environment, but I'll look into that next.

**Comment by rnbguy** [comment]
No worries for lockfile. I just didn't check if you're using it or not. But in the downstream, if you have a binary crate with rust docs, then you have to run `cargo update` to update its lockfile.

For the docs.rs, crate-owners can not trigger a fresh `cargo doc` build for a failed one [... yet](https://github.com/rust-lang/docs.rs/issues/301#issue-410542585). So you have to wait till the next release on crates-io.

**Comment by conorsch** [comment]
Docs no longer failing, closing.
