### ISSUE TITLE
Tracking Issue: split out IBC subcrates

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/ibc-types#8]
We want to split the current `ibc-types` crate into subcrates with a coherent dependency graph. At a high level, the plan is to create subcrates like `ibc-types-core-client`, `ibc-types-lightclients-tendermint`, etc, which can depend on each other, and then to re-export their contents in a unified `ibc-types` "parent" crate that can depend on all of them. The `ibc-types` "parent" crate can also define alternate versions of some message types, e.g., with explicit enumerations of different client types, so that it's not necessary to type-erase all of the client state to avoid circular dependencies involving external clients.

Suggested priority list (subject to evolution):

- [x] `ibc-types-core-client`
- [x] `ibc-types-core-connection`
- [x] #18
- [x] #14
- [ ] ???

**Comment by conorsch** [comment]
We've completed this, including the above tracked tasks and several more.
